services:
  servidor:
    container_name: servidor
    image: rovela/php:8.5-fpm-alpine3.23
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/public
    external_links:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8089:80"
    working_dir: /var/www/html/public
    deploy:
      resources:
        limits:
          memory: 2GB
        reservations:
          memory: 1GB

networks:
  default:
    external: true
    name: uni_sup_network
